config/routes.rb
Rails::Application.routes.draw do

  resources :workitems
  resources :tasks
  resources :processes
  resources :forms
  resources :definitions do
      member do
        get 'launch' 
      end
  end
  # ruote-kit
  #
  match '/_ruote' => RuoteKit::Application
  match '/_ruote/*path' => RuoteKit::Application

  # login / logout
  #
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  # /
  #
  root :to => 'tasks#index'
  
  match ':controller/:action/:id'
  match ':controller/:action'
  match 'tasks/*path/:id' => 'tasks#edit'
end

app/controllers/tasks_controller.rb
class TasksController < TaskFormController
  
  def index

    current_page = 1
    current_page = params[:page].to_f unless params[:page].nil?
    per_page = ITEMS_PER_PAGE 
    
    user_or_group = params[:group]
    user_or_group ||= session[:username]
    unless params[:group].blank? or params[:group] == "anyone" or User.find(session[:username]).groups.include? user_or_group
        render :text => "No access", :status => :forbidden
      else 
  
      @workitems = WillPaginate::Collection.create(current_page, per_page) do |pager|
  
        result = Ruote::Workitem.for_user(user_or_group,{:skip => pager.offset, :limit => pager.per_page},params[:all_users])
        pager.replace(result)
      
        unless pager.total_entries
          pager.total_entries = Ruote::Workitem.for_user_count(user_or_group,{},params[:all_users])
        end
      end
      
      respond_to do |format|
        format.html
        format.js {
          render :update do |page|
            page.replace 'results', :partial => 'search_results'
          end
        }
      end
    end
  end
  def edit

    @workitem =
      RuoteKit.storage_participant[params[:id]]
    @tree =
      Rufus::Json.encode(RuoteKit.engine.process(@workitem.wfid).current_tree)
  end
  class Base < TaskFormController
    layout 'tasks_base'
    helper :tasks
    
    def index
      redirect_to :controller => :tasks, :action => :index
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_buttons(opts = {})
    workitem = opts[:workitem]
    workitem ||= @workitem
    answer_var = opts[:answer_var]
    answer_var ||= "answer"

    render :partial => "/tasks/buttons", :locals => {
        :workitem => workitem, 
        :answers => opts[:answers], 
        :answer_var => answer_var,
      }
  end
end

app/views/tasks/_buttons.haml
.buttons

  = link_to t('tasks.edit.cancel'), :action => :index

  = submit_tag t('tasks.edit.save'), :name => 'save_subaction'
  - if answers.blank?
    = submit_tag t('tasks.edit.proceed'), :name => 'proceed_subaction'
  - else
    - answers.each do |answer|
      = submit_tag t("tasks.edit.answer.#{answer}"), :name => "proceed_subaction/#{answer_var}/#{answer}"

app/views/tasks/_search_results.haml
.results
  = will_paginate @workitems
  %table.list
  
    %thead
      %td 
        = t '.title'
      %td
        = t '.participant_name'
      %td
        = t '.task'
      %td
  
    - @workitems.each do |workitem|
      %tr
        %td
          - unless workitem.params['task'].blank?
            - begin
              = render :partial => "tasks/#{workitem.params['task']}/title", 
              :locals => { :task_fields => workitem.fields, :workitem => workitem} 
            - rescue ActionView::MissingTemplate
              = workitem.params['task']
        %td
          = workitem.participant_name
        %td
          = workitem.params['task']
        %td
          - unless workitem.params['task'].blank?
            - if workitem.participant_name == session[:username]
              = link_to t('.edit'), :controller => "tasks/"+workitem.params['task'],:action => "edit", :id => workitem.fei.sid
              = link_to t('.unclaim'), :controller => "tasks/"+workitem.params['task'],:action => "unclaim", :id => workitem.fei.sid
            - else
              = link_to t('.claim'), :controller => "tasks/"+workitem.params['task'],:action => "claim", :id => workitem.fei.sid
              = link_to t('.claim&edit'), :controller => "tasks/"+workitem.params['task'],:action => "claim", :id => workitem.fei.sid, :edit =>true
          -else
            = link_to t('.show'), task_path(workitem)
  = will_paginate @workitems

app/views/tasks/edit.haml
#flow
  %canvas#fluo{ :width => 1150, :height => 700 }
  
%h1
  = t '.title'

#form

  -form_tag({:action => :update}, :method => :put) do

    %div #{t('.fields') + ':'}
    = text_area_tag 'workitem[fields]', Rufus::Json.encode(@workitem.fields), :rows => 10, :cols => 77

    = task_buttons(@workitem)

      
:javascript  
    //
  // fluo


  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow(
    'fluo', #{@ruote_process_state_tree}, { workitems: [ '#{@workitem.fei.expid}' ] });
  
  Fluo.crop('fluo');

app/views/tasks/index.haml
= render 'search_results'

app/views/tasks/show.haml
#flow
  %canvas#fluo{ :width => 1150, :height => 700 }
  
%h1
  = t '.title'

#form

  -form_tag({:action => :update}, :method => :put) do

    %div #{t('.fields') + ':'}
    = text_area_tag 'workitem[fields]', Rufus::Json.encode(@workitem.fields), :rows => 10, :cols => 77

    = task_buttons(@workitem)

      
:javascript  
    //
  // fluo


  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow(
    'fluo', #{@ruote_process_state_tree}, { workitems: [ '#{@workitem.fei.expid}' ] });
  
  Fluo.crop('fluo');