config/routes.rb
Rails::Application.routes.draw do

  resources :workitems
  resources :tasks
  resources :processes
  resources :forms
  resources :definitions do
      member do
        get 'launch' 
      end
  end
  # ruote-kit
  #
  match '/_ruote' => RuoteKit::Application
  match '/_ruote/*path' => RuoteKit::Application

  # login / logout
  #
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  # /
  #
  root :to => 'tasks#index'
  
  match ':controller/:action/:id'
  match ':controller/:action'
  match 'tasks/*path/:id' => 'tasks#edit'
end

app/controllers/definitions_controller.rb
#
# process definitions
#
class DefinitionsController < RailsBpmController

  def index

    @definitions = RailsBpm::Process.all
  end

  def show

    @definition = RailsBpm::Process.find(params[:id])
  end
  def launch
    redirect_to :controller => 'processes', :action => 'create', :definition => params[:id]
  end
end

app/views/definitions/index.haml
%h1
  = t '.title'

%table.list

  %thead
    %td
      = t 'definition.id'
    %td
      = t 'definition.name'
    %td
      = t 'definition.revision'
    %td

  - @definitions.each do |definition|
    %tr
      %td
        = definition.id
      %td
        = definition.name
      %td
        = definition.revision
      %td
        .buttons
          = link_to t('.show'), definition_path(definition.id)
          = button_to t('.launch'), processes_path(:definition => definition.id) 

app/views/definitions/show.haml
%h1
  = t '.title'

#flow
  %canvas#fluo{ :width => 200, :height => 200 }

%pre#definition #{@definition.definition}

.buttons
  = link_to t('.back'), :action => :index
  = button_to t('.launch'), processes_path(:definition => @definition.id)


:javascript

  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow('fluo', #{Ruote::Reader.read(@definition.definition).to_json})
  Fluo.crop('fluo');