config/routes.rb
Rails::Application.routes.draw do

  resources :workitems
  resources :tasks
  resources :processes
  resources :forms
  resources :definitions do
      member do
        get 'launch' 
      end
  end
  # ruote-kit
  #
  match '/_ruote' => RuoteKit::Application
  match '/_ruote/*path' => RuoteKit::Application

  # login / logout
  #
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  # /
  #
  root :to => 'tasks#index'
  
  match ':controller/:action/:id'
  match ':controller/:action'
  match 'tasks/*path/:id' => 'tasks#edit'
end

app/views/layouts/rails_bpm.haml
%html

  %head

    %meta( http-equiv="Content-Type" content="text/html; charset=UTF-8" )

    %title Rails BPM

    %link( href='/images/favicon.png' type='image/png' rel='icon' )
    = stylesheet_link_tag 'reset', 'rails_bpm', 'formtastic', 'formtastic_changes'
    /[if !IE7]
      :css
        .container { display: table; height: 100%; }

    %script{ :src => '/_ruote/javascripts/ruote-fluo.js' }
    %script{ :src => '/javascripts/rails_bpm.js' }


  %body

    .container

      .header
        %a.home{ :href => '/' }
          %img{ :src => '/images/ruote.png', :alt => 'rails-bpm' }
          
      - if session[:username]
        %a.button.user{ :href => '/logout' } #{t('.logout')} #{session[:username]}
        .nav
          %ul
            %li
              = link_to t('.definitions'), definitions_path
            %li
              .task_nav
                %a  #{t('.tasks')}
                
                %ul
                  %li
                    = link_to  t('.my_tasks'), tasks_path
                  - user = User.find(session[:username])
                  - user.groups.each do |group|
                    %li
                      = link_to  group, tasks_path({:group => group})
                  %li 
                    = link_to  t('.anyone'), tasks_path({:group => 'anyone'})
                  %li 
                    = link_to  t('.all'), tasks_path({:all_users => true}) if user.admin?
            %li
              = link_to t('.processes'), processes_path
            - if User.admin?(session[:username])
              %li
                = link_to t('.ruote'), '/_ruote'

      = render :partial => 'shared/flash'

      .main_content
        = content_for?(:content) ? yield(:content) : yield(:layout)

    .footer
      %p
        powered by
        %a{ :href => 'http://ruote.rubyforge.org' }
          ruote
        and
        %a{ :href => 'http://github.com/tosch/ruote-kit' }
          ruote-kit

app/views/layouts/tasks_base.haml
- content_for :content do
  #flow
    %canvas#fluo{ :width => 1150, :height => 700 }
  = yield(:layout)
      
  :javascript  
    //
    // fluo
  
  
    document.getElementById('fluo').noOuterBorder = true;
    
    Fluo.renderFlow(
      'fluo', #{@ruote_process_state_tree}, { workitems: [ '#{@workitem.fei.expid}' ] });
    
    Fluo.crop('fluo');
    
=render :file => 'layouts/rails_bpm'